version: '3'
services:
  umami:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_TYPE: postgresql
        BASE_PATH: /umami
    container_name: umami
    network_mode: host
    restart: always
    environment:
      HOSTNAME: 127.0.0.1
      PORT: 3002
      DATABASE_URL: postgresql://umami:umami@127.0.0.1:5432/umami
      DATABASE_TYPE: postgresql
      APP_SECRET: NXGqZNVlH0hMpjQwwfYQ
      DISABLE_TELEMETRY: 1
